apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

android {
    namespace "org.prebid.veondemo"
    setCompileSdkVersion(34)
    defaultConfig {
        minSdk 29
        targetSdkVersion 34
        versionCode 1
        versionName "1.0.0"
        applicationId "org.prebid.veondemo"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    buildFeatures {
        dataBinding true
    }
    // Fix for Exoplayer Problem
    packagingOptions {
        exclude("META-INF/*.kotlin_module")
    }
    buildTypes {
        release {
            signingConfig signingConfigs.debug
        }
    }
}

dependencies {
    implementation project(':PrebidMobile')
    implementation project(':PrebidMobile-gamEventHandlers')

//    implementation 'com.github.veonadtech.prebid-android-sdk:mobile:0.1.1-yango'
//    implementation 'com.github.veonadtech.prebid-android-sdk:core:0.1.1-yango'
//    implementation 'com.github.veonadtech.prebid-android-sdk:eventhandlers:0.1.1-yango'
//    implementation 'com.github.veonadtech.prebid-android-sdk:prebidorg:0.1.1-yango'

    // Standard libraries
    implementation libs.kotlin.stdlib
    implementation libs.androidx.appcompat
    implementation libs.androidx.preference.ktx
    implementation libs.androidx.constraintlayout
    implementation libs.androidx.lifecycle.viewmodel.ktx

    // Advertisement
    implementation libs.google.play.services.base
    implementation libs.google.play.services.ads
    implementation libs.google.play.services.ads.identifier
    implementation libs.applovin.sdk

    // Yandex Mobile Ads SDK core lib
    implementation libs.yandex.ads
    implementation libs.yandex.ads.bigoads
    implementation libs.yandex.ads.google
    implementation libs.yandex.ads.vungle
    implementation libs.yandex.ads.mintegral
    implementation (libs.yandex.ads.extras){
        exclude group: "com.facebook.android", module: "audience-network-sdk"
        exclude group: "com.unity3d.mediation", module: "facebookadapter"
        exclude group: "com.inmobi.monetization", module: "inmobi-ads-kotlin"
        exclude group: "com.unity3d.mediation", module: "inmobiadapter"
        exclude group: "com.mbridge.msdk.oversea"
        exclude group: "com.unity3d.mediation", module: "mintegraladapter"
        exclude group: "com.pangle.global", module: "ads-sdk"
        exclude group: "com.unity3d.mediation", module: "pangleadapter"
        exclude group: "com.chartboost", module: "chartboost-sdk"
        exclude group: "com.unity3d.mediation", module: "chartboost-adapter"
        exclude group: "com.applovin", module: "applovin-sdk"
        exclude group: "com.unity3d.mediation", module: "applovin-adapter"
    }

    implementation libs.facebook.audience

    // Image Downloader
    implementation libs.glide

    // Multidex
    implementation libs.androidx.multidex

    // Video Player
    implementation libs.exoplayer
    implementation libs.exoplayer.dash
    implementation libs.exoplayer.ima
    implementation libs.exoplayer.ui
    implementation libs.interactive.media

    // Tests
    testImplementation libs.junit
    testImplementation libs.androidx.junit
    testImplementation libs.androidx.espresso.core
    testImplementation libs.androidx.uiautomator
}
