apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

android {
    namespace "org.prebid.veondemo"
    setCompileSdkVersion(34)
    defaultConfig {
        minSdk 29
        targetSdkVersion 34
        versionCode 1
        versionName "1.0.0"
        applicationId "org.prebid.veondemo"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    buildFeatures {
        dataBinding true
    }
    // Fix for Exoplayer Problem
    packagingOptions {
        exclude("META-INF/*.kotlin_module")
    }
    buildTypes {
        release {
            signingConfig signingConfigs.debug
        }
    }
    lint {
        baseline = file("lint-baseline.xml")
        checkReleaseBuilds = false
    }
}

dependencies {
    implementation project(':PrebidMobile')
    implementation project(':PrebidMobile-gamEventHandlers')

//    implementation 'com.github.veonadtech.prebid-android-sdk:mobile:0.3.0'
//    implementation 'com.github.veonadtech.prebid-android-sdk:core:0.3.0'
//    implementation 'com.github.veonadtech.prebid-android-sdk:eventhandlers:0.3.0'
//    implementation 'com.github.veonadtech.prebid-android-sdk:prebidorg:0.3.0'

    // Standard libraries
    implementation libs.kotlin.stdlib
    implementation libs.androidx.appcompat
    implementation libs.androidx.preference.ktx
    implementation libs.androidx.constraintlayout
    implementation libs.androidx.lifecycle.viewmodel.ktx

    // Advertisement
    implementation libs.google.play.services.base
    implementation libs.google.play.services.ads
    implementation libs.google.play.services.ads.identifier
   // implementation libs.applovin.sdk

    // Yandex Mobile Ads SDK core lib
    implementation(libs.yandex.ads) {
        exclude group: "com.yandex.ads.mediation", module: "mobileads-applovin"
        exclude group: "com.yandex.ads.mediation", module: "mobileads-appnext"
        exclude group: "com.yandex.ads.mediation", module: "mobileads-chartboost"
        exclude group: "com.yandex.ads.mediation", module: "mobileads-google"
        exclude group: "com.yandex.ads.mediation", module: "mobileads-inmobi"
        exclude group: "com.yandex.ads.mediation", module: "mobileads-mytarget"
        exclude group: "com.yandex.ads.mediation", module: "mobileads-pangle"
        exclude group: "com.yandex.ads.mediation", module: "mobileads-tapjoy"
        exclude group: "com.yandex.ads.mediation", module: "mobileads-unityads"
    }
    implementation (libs.yandex.ads.extras) {
        exclude group: "com.inmobi.monetization", module: "inmobi-ads-kotlin"
        exclude group: "com.ironsource.adapters", module:  "admobadapter"
        exclude group:  "com.google.android.gms", module:  "play-services-ads"
        exclude group:  "com.ironsource.adapters", module:  "facebookadapter"
        exclude group:  "com.facebook.android", module:  "audience-network-sdk"
        exclude group:  "com.ironsource.adapters", module:  "fyberadapter"
        exclude group:  "com.fyber", module:  "marketplace-sdk"
        exclude group:  "com.ironsource.adapters", module:  "inmobiadapter"
        exclude group:  "com.ironsource.adapters", module:  "pangleadapter"
        exclude group:  "com.ironsource.adapters", module:  "unityadsadapter"
        exclude group:  "com.mbridge.msdk.oversea", module:  "mbbanner"
        exclude group:  "com.mbridge.msdk.oversea", module:  "mbbid"
        exclude group:  "com.mbridge.msdk.oversea", module:  "newinterstitial"
        exclude group:  "com.mbridge.msdk.oversea", module:  "reward"
        exclude group:  "com.pangle.global", module:  "ads-sdk"
        exclude group:  "com.unity3d.ads", module:  "unity-ads"
    }
    implementation("com.yandex.android:mobileads") {
        version {
            strictly("7.9.0")
        }
    }
    implementation("io.appmetrica.analytics:analytics") {
        version {
            strictly("7.9.0")
        }
    }

    //implementation libs.facebook.audience

    // Image Downloader
    implementation libs.glide

    // Multidex
    implementation libs.androidx.multidex

    // Video Player
    implementation libs.exoplayer
    implementation libs.exoplayer.core
    implementation libs.exoplayer.ui
    implementation libs.extension.ima

    // Tests
    testImplementation libs.junit
    testImplementation libs.androidx.junit
    testImplementation libs.androidx.espresso.core
    testImplementation libs.androidx.uiautomator
}
