apply plugin: 'com.android.library'
apply plugin: 'maven-publish'

android {
    setCompileSdkVersion(rootProject.prebidSdkCompileVersion)
    setBuildToolsVersion(rootProject.prebidSdkBuildToolsVersion)

    defaultConfig {
        minSdkVersion rootProject.prebidSdkMinVersion
        targetSdkVersion rootProject.prebidSdkTargetVersion
        versionCode 1
        versionName rootProject.prebidSdkVersionName
    }

    buildTypes {
        debug {
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            consumerProguardFiles file('proguard-rules.pro')
        }
        release {
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            consumerProguardFiles file('proguard-rules.pro')
        }
    }

    lintOptions {
        abortOnError false
    }

    testOptions.unitTests {
        includeAndroidResources true
        returnDefaultValues = true
        all {
            systemProperty 'robolectric.dependency.repo.url', 'https://repo1.maven.org/maven2'
            testLogging {
                events "passed", "skipped", "failed", "standardOut", "standardError"
                exceptionFormat = "full"
            }
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    packagingOptions {
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/INDEX.LIST'
        exclude 'META-INF/LICENSE'
    }
}

afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                groupId = "org.prebid"
                artifactId = "prebid-mobile-sdk-core"
                version = rootProject.prebidSdkVersionName

                from components.release

                pom {
                    name = "Prebid Mobile SDK Core"
                    description = "Core module of the Prebid Mobile SDK"
                    url = "https://github.com/prebid/prebid-mobile-android"
                    licenses {
                        license {
                            name = "The Apache License, Version 2.0"
                            url = "http://www.apache.org/licenses/LICENSE-2.0.txt"
                        }
                    }
                    developers {
                        developer {
                            id = "prebid"
                            name = "Prebid.org"
                            email = "mobile@prebid.org"
                        }
                    }
                    scm {
                        connection = "scm:git:git://github.com/prebid/prebid-mobile-android.git"
                        developerConnection = "scm:git:ssh://github.com/prebid/prebid-mobile-android.git"
                        url = "https://github.com/prebid/prebid-mobile-android"
                    }
                }
            }
        }
    }
}