apply from: 'android.gradle'
apply from: 'publisher.gradle'

android {
    namespace "org.prebid.mobile"
}

dependencies {
    api project(':PrebidMobile-core')
}

// Main SDK artifact configuration
publishing {
    publications {
        maven(MavenPublication) {
            afterEvaluate {
                from components.release
            }
            
            groupId = rootProject.ext.artifactGroupId
            artifactId = 'prebid-mobile-sdk'
            version = rootProject.ext.prebidSdkVersionName
            
            artifact sourcesJar
            artifact javadocJar
        }
    }
}