apply from: '../android.gradle'
apply from: '../publisher.gradle'

dependencies {
    implementation project(":PrebidMobile")
    implementation libs.google.play.services.ads
}

android {
    namespace "org.prebid.mobile.eventhandlers"
    defaultConfig {
        namespace 'org.prebid.mobile.eventhandlers'
        minSdkVersion 19
    }
    testOptions {
        unitTests.all {
            jvmArgs '--add-opens=java.base/java.lang=ALL-UNNAMED'
            systemProperty 'robolectric.invokedynamic.enable', 'false'
        }
    }
}

afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                from components.release
                groupId = "org.prebid.mobile"
                artifactId = "eventhandlers"
                version = '1.0.0'
            }
        }
    }
}