apply from: '../android.gradle'
apply from: '../publisher.gradle'
apply from: '../tests.gradle'
apply plugin: 'org.jetbrains.kotlin.android'

android {
    namespace "org.prebid.mobile.core"

    buildFeatures {
        buildConfig true
    }

    def getGitHash = { ->
        def stdout = new ByteArrayOutputStream()
        exec {
            commandLine 'git', 'rev-parse', '--short', 'HEAD'
            standardOutput = stdout
        }
        return stdout.toString().trim()
    }
    kotlinOptions {
        jvmTarget = '17'
    }

    defaultConfig {
        buildConfigField "String", "GitHash", "\"${getGitHash()}\""
        buildConfigField "String", "VERSION", "\"${versionName}\""
        buildConfigField "String", "OMSDK_VERSION", "\"${omSdkVersion}\""
        multiDexEnabled true
    }
    testOptions {
        unitTests.all {
            jvmArgs '--add-opens=java.base/java.lang=ALL-UNNAMED'
            systemProperty 'robolectric.invokedynamic.enable', 'false'
        }
    }
}


dependencies {
    implementation project(":omsdk-android")

    implementation libs.androidx.annotation

    implementation libs.guava
    implementation libs.concurrent.futures

    implementation libs.google.play.services.base
    implementation libs.google.play.services.ads
    implementation libs.google.play.services.ads.identifier

    implementation libs.exoplayer
    implementation libs.exoplayer.ui

    implementation libs.androidx.localbroadcastmanager

    // Yandex Mobile Ads SDK core lib
    implementation(libs.yandex.ads) {
        exclude group: "com.yandex.ads.mediation", module: "mobileads-applovin"
        exclude group: "com.yandex.ads.mediation", module: "mobileads-appnext"
        exclude group: "com.yandex.ads.mediation", module: "mobileads-chartboost"
        exclude group: "com.yandex.ads.mediation", module: "mobileads-google"
        exclude group: "com.yandex.ads.mediation", module: "mobileads-inmobi"
        exclude group: "com.yandex.ads.mediation", module: "mobileads-mytarget"
        exclude group: "com.yandex.ads.mediation", module: "mobileads-pangle"
        exclude group: "com.yandex.ads.mediation", module: "mobileads-tapjoy"
        exclude group: "com.yandex.ads.mediation", module: "mobileads-unityads"
    }
}

configurations.all {
    resolutionStrategy.eachDependency { details ->
        if (details.requested.group == 'com.google.guava' && details.requested.name == 'listenablefuture') {
            details.useTarget('androidx.concurrent:concurrent-futures:1.1.0')
            details.because('Use androidx.concurrent.futures instead of guava listenablefuture to avoid conflicts')
        }
    }
}

afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                from components.release
                groupId = "org.prebid.mobile"
                artifactId = "core"
                version = '1.0.0'
            }
        }
    }
}