apply from: '../android.gradle'
apply from: '../publisher.gradle'
apply from: '../tests.gradle'

apply plugin: 'maven-publish'

android {
    namespace "org.prebid.mobile.core"

    buildFeatures {
        buildConfig true
    }

    def getGitHash = { ->
        def stdout = new ByteArrayOutputStream()
        exec {
            commandLine 'git', 'rev-parse', '--short', 'HEAD'
            standardOutput = stdout
        }
        return stdout.toString().trim()
    }

    defaultConfig {
        buildConfigField "String", "GitHash", "\"${getGitHash()}\""
        buildConfigField "String", "VERSION", "\"${versionName}\""
        buildConfigField "String", "OMSDK_VERSION", "\"${omSdkVersion}\""
    }
}

dependencies {
    implementation project(":omsdk-android")

    implementation 'androidx.annotation:annotation:1.5.0'

    implementation 'com.google.android.gms:play-services-base:18.1.0'
    implementation 'com.google.android.gms:play-services-ads-identifier:18.0.1'
    implementation 'com.google.android.exoplayer:exoplayer-core:2.19.1'
    implementation 'com.google.android.exoplayer:exoplayer-ui:2.19.1'

    implementation "androidx.localbroadcastmanager:localbroadcastmanager:1.0.0"
}

publishing {
    publications {
        core(MavenPublication) {
            groupId = 'com.github.veonadtech.prebid-android-sdk'
            artifactId = 'core'
            version = 'v0.0.3.7-gradle-8.2.x'
            artifact("$buildDir/outputs/aar/PrebidMobile-core-release.aar")

            pom.withXml {
                def deps = asNode().appendNode('dependencies')
                configurations.implementation.allDependencies.each { dep ->
                    if (dep.name != 'unspecified' && dep.group != null) {
                        def depNode = deps.appendNode('dependency')
                        depNode.appendNode('groupId', dep.group)
                        depNode.appendNode('artifactId', dep.name)
                        depNode.appendNode('version', dep.version)
                    }
                }
            }
        }
    }
}